# Generated by Django 4.2.13 on 2024-06-01 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='coffeeapp/')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[{'cappuccino', 'CA'}, {'latte', 'LT'}, {'ES', 'espresso'}, {'BL', 'black'}], max_length=20)),
            ],
        ),
    ]
