# Generated by Django 4.2.13 on 2024-06-01 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_coffee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='type',
            field=models.CharField(choices=[('CA', 'cappuccino'), ('LT', 'latte'), ('ES', 'espresso'), ('BL', 'black')], max_length=2),
        ),
        migrations.CreateModel(
            name='CoffeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('rating', models.IntegerField()),
                ('given_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.coffee')),
            ],
        ),
    ]
